### ISSUE TITLE
Bug: Missing testbeds schema dependency

### ISSUE THREAD

**Issue by JensRoland** [aorwall/moatless-tree-search#12]
In the[ Claude 3.5 Sonnet PR](https://github.com/aorwall/moatless-tree-search/pull/4) it seems the dependency on the `testbeds` package was removed.

With this package missing, the Streamlit app now crashes on launch with the following error:

```shell
    from moatless.file_context import FileContext
  File "/Users/jensr/Documents/Deep Quantum/Coding Agents/moatless-tree-search/moatless/file_context.py", line 27, in <module>
    from testbeds.schema import TestStatus
ModuleNotFoundError: No module named 'testbeds'
```

It seems the `testbeds.schema` is required even if you aren't using the Moatless Testbeds.

**Comment by JensRoland** [comment]
FYI I re-added the dependency in [this PR](https://github.com/aorwall/moatless-tree-search/pull/13).

**Comment by aorwall** [comment]
Thanks! I merged your PR.
