### ISSUE TITLE
moatless-tree-search implementation status

### ISSUE THREAD

**Issue by thanhhau097** [aorwall/moatless-tree-search#15]
Hi authors,

Thanks for really great work here. 

I'm just wondering about the state of current `main` branch of the repo. Did it finish replicate the code of `swesearch`? I also saw that you are actively developing on some branches. Any suggestion to start with the current codebase?

Thank you!!!

**Comment by aorwall** [comment]
It's not an exact copy of SWE-search but rather a refactor to make it easier to extend. It's also somewhat of a moving target where the focus is on finding new optimizations to solve coding tasks (higher scores on SWE-bench), but also to be able to use it for purposes other than just coding. However, main is still the branch that should remain stable. I'll try to merge some changes from the other active branches in the coming days to handle multiple tool calls and fix some bugs.​​​​​​​​​​​​​​​​

**Comment by thanhhau097** [comment]
Thank you!!! Do we have the swebench experiment score on current `main` or any branches?

**Comment by aorwall** [comment]
Just running on basic flow with Claude 3.5 sonnet, without tree search. It’s at 38% on “lite” from the latest submission to Swebench.
